title: My Name
logo: ./photo.webp
description: text below image
# show_downloads: true
theme: jekyll-theme-minimal
#remote_theme: pages-themes/tactile@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
